version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: prolosaures-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - prolosaures-network
        environment:
            - APP_ENV=local
            - APP_KEY=base64:mycuskey
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3309
            - DB_DATABASE=prolosaures
            - DB_USERNAME=root
            - DB_PASSWORD=root

    db:
        image: mysql:5.7
        container_name: prolosaures-db
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: prolosaures
        ports:
            - "3309:3309"
        networks:
            - prolosaures-network

    nginx:
        image: nginx:alpine
        container_name: prolosaures-nginx
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8200:80"
        networks:
            - prolosaures-network
        depends_on:
            - app

networks:
    prolosaures-network:
        driver: bridge

volumes:
    dbdata:
